### ISSUE TITLE
opencart 2.0

### ISSUE THREAD

**Issue by mischievous** [simplifycom/simplify-opencart-module#1]
The current version does now work with opencart 2.0

**Comment by siddii** [comment]
Hi @mischievous,

The error is due to changes to CakePHP - http://stackoverflow.com/questions/9629013/notice-8-indirect-modification-of-overloaded-property

I am currently looking at the impact & changes need to update the plugin.

**Comment by mischievous** [comment]
Thank you for getting back too me.   I have gotten the admin view working, which i suspect was the easy part now.   

I will be happy to sent you my changes, but last time i tried to use github I caused nothing but problems and gave up.

**Comment by siddii** [comment]
Sure, feel free to attach the patch file or send a PR

**Comment by mischievous** [comment]
Sorry... I hate github... This was suppose to be for simplifycom/simplify-opencart-module.   Grr...

**Comment by mischievous** [comment]
God!  I hate webdev!  But I think I have it all setup and working.  I can go from the admin page where everything get configured, to the cart checkout, to checkout/success.  I hope I did not breaking anything in the process.  I will try to make a patch file an upload it to here tomorrow.

**Comment by tpsjr7** [comment]
We've pushed the v1.0.5 release to be compatible with OpenCart 2.0. Closing ticket.
