### ISSUE TITLE
Version v1.2.1 is not keep the radio button

### ISSUE THREAD

**Issue by petp3t** [simplifycom/simplify-opencart-module#11]
Version v1.2.1 is not keep the radio button 
in
Payment Mode: Hosted Payments or Standard
stay always in hosted Payments

**Comment by JohnbConneely** [comment]
Hey @petp3t, this is by design. Standard payment form has been removed as it was not conforming with PCI certification. 
Standard payment forms will no longer be supported on the plugin.
