### ISSUE TITLE
Page cannot be scrolled after button colour change on "Confirm Order" page

### ISSUE THREAD

**Issue by AlNotSteve** [simplifycom/simplify-opencart-module#12]
Hi,

When going through the ordering process, all pages are scrollable except for the "Confirm Order" page.  Scrolling breaks after the "Confirm Order" button changes to the colour set in the plugin.

Opencart version: 3.0.3.3

![Screenshot from 2020-05-29 10-55-56](https://user-images.githubusercontent.com/33239282/83209995-0724a180-a19d-11ea-8150-8da1430bddf0.jpg)

**Comment by JohnbConneely** [comment]
Hey @AlNotSteve,

Are you still encountering this issue? If you are, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
