### ISSUE TITLE
Opencart 2.3.0.2 and simplify-opencart-module-1.2.1

### ISSUE THREAD

**Issue by kpanosgr** [simplifycom/simplify-opencart-module#13]
After successful install and admin settings, on checkout page after clicking SUBMIT ORDER, nothing happens. No errors is javascript console. Just a frozen page. I see that the simplify code in html is twice added. Need to add/alter something to code? Opencart theme is Journal.

**Comment by iliasvlachos** [comment]
Having the same issue on opencart 2.3.0.2 with journal theme 2.16
I am using one page checkout.
Tried the plugin with Hosted payments and standard.

**Comment by kpanosgr** [comment]
it seems that with one page checkout on journal theme, the plugin's payment button is hidden. you have to show it with css and don't use the theme's checkout button. Nevertheless, the payment cannot complete, there is still problem.

**Comment by JohnbConneely** [comment]
Hey @kpanosgr/ @iliasvlachos ,

Are you still having this issue? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
