### ISSUE TITLE
Compatibility with OC 2.1.0.2 - Installments

### ISSUE THREAD

**Issue by kstampo** [simplifycom/simplify-opencart-module#9]
Hi,
Looks like the plugin is not compatible with opencart 2.1.0.2. Is it true?
Also, does it support installments?

**Comment by JohnbConneely** [comment]
Hey @kstampo the plugin should be compatible with the most recent stable version of opencart.
With regards to installments, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
